services:
    backend:
        image: ghcr.io/xwillq/dev-environment/php/8.1-rr:latest
        container_name: backend
        restart: on-failure
        logging:
            driver: local
        environment:
            PHP_IDE_CONFIG: serverName=laravel.test
            PHP_MEMORY_LIMIT: 128M
        volumes:
            - code:/app
        networks:
            - main
        command: php artisan octane:start --host 0.0.0.0 --workers 1 --max-requests 1
        labels:
            - traefik.enable=true

            - traefik.http.routers.backend.rule=Host(`laravel.test`)
            - traefik.http.routers.backend.entrypoints=websecure
            - traefik.http.services.backend.loadbalancer.server.port=8000
networks:
    main:
        external: true
        name: main

volumes:
    code:

x-mutagen:
    sync:
        defaults:
            scanMode: full
            ignore:
                vcs: true
                paths:
                    - "*.sql"
            mode: two-way-resolved

        code:
            alpha: .
            configurationAlpha:
                permissions:
                    defaultFileMode: 0o644
                    defaultDirectoryMode: 0o755
            beta: volume://code
            configurationBeta:
                permissions:
                    defaultOwner: id:82
                    defaultGroup: id:82
                    defaultFileMode: 0o644
                    defaultDirectoryMode: 0o755

    sidecar:
        restart: on-failure
